// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Programacion3MovilCrudAPI.Models;

public partial class Fertilizantes
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Forma { get; set; }

    public string Composicion { get; set; }

    public string Tipo { get; set; }

    public string Descripcion { get; set; }
}