// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Programacion3MovilCrudAPI.Models;

public partial class Plantas
{
    public int Id { get; set; }

    public string NombreCientifico { get; set; }

    public string NombreVulgar { get; set; }

    public string Autor { get; set; }

    public string EpocaFloracion { get; set; }

    public int? AlturaMaxima { get; set; }

    public string Descripcion { get; set; }
}